create table if not exists public.trip_history (
  id bigint generated by default as identity primary key,
  user_id uuid not null,
  origin text not null,
  destination text not null,
  distance_km numeric(8,2) not null default 0,
  fare_estimate numeric(8,2) not null default 0,
  modes_used text[] not null default '{}',
  created_at timestamptz not null default now()
);

alter table public.trip_history enable row level security;

create policy "Users can view own trip_history"
  on public.trip_history
  for select
  using (auth.uid() = user_id);

create policy "Users can insert own trip_history"
  on public.trip_history
  for insert
  with check (auth.uid() = user_id);

create policy "Users can delete own trip_history"
  on public.trip_history
  for delete
  using (auth.uid() = user_id);
